sudo: required

language: go

env:
  global:
    - IMAGE_NAME=storageos/nfs
    - IMAGE_TAG=test
    - K8S_VERSION="v1.14.2"

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.MD)|(\.png)|(\.pdf)|^(doc/)|^(MAINTAINERS)|^(LICENSE)'; then
          echo "Only doc files were updated, not running the CI."
          exit
      fi

jobs:
  include:
    - script: ./e2e.sh
    - stage: deploy
      script:
        - make image
      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        - provider: script
          script: bash deploy.sh tagged
          on:
            tags: true
        - provider: script
          script: bash deploy.sh develop
          on:
            branch: master