FROM golang:1.12.7 AS build
WORKDIR /go/src/github.com/storageos/nfs/
COPY . /go/src/github.com/storageos/nfs/
RUN make build

# just update go binary
FROM storageos/nfs:test

COPY --from=build /go/src/github.com/storageos/nfs/build/_output/bin/nfs /nfs

# NFS port and http daemon
EXPOSE 2049 80

# Start Ganesha NFS daemon by default
CMD ["/nfs"]
