[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[prune]
  go-tests = true
  unused-packages = true
